// Catálogo de apoyo del curso; IDs internos, no identificadores oficiales AGESIC.
export const CONTROLES_MCU = [
  {
    controlId: 'GV-01',
    funcion: 'Gobernar',
    codigo: 'GV',
    tema: 'Política de ciberseguridad aprobada y comunicada',
    evidenciaNecesaria: 'Política firmada',
    demostracionSugerida:
      'Presentar la política aprobada con fecha y firma de la Dirección',
  },
  {
    controlId: 'GV-02',
    funcion: 'Gobernar',
    codigo: 'GV',
    tema: 'Estrategia de ciberseguridad alineada al negocio',
    evidenciaNecesaria: 'Estrategia/plan anual',
    demostracionSugerida:
      'Mostrar el plan anual y su presentación a la Dirección',
  },
  {
    controlId: 'GV-03',
    funcion: 'Gobernar',
    codigo: 'GV',
    tema: 'Roles y responsabilidades claros (RSI, comité, dueños)',
    evidenciaNecesaria: 'Matriz RACI / organigrama',
    demostracionSugerida:
      'Desplegar la matriz RACI con responsables por proceso',
  },
  {
    controlId: 'GV-04',
    funcion: 'Gobernar',
    codigo: 'GV',
    tema: 'Programa de gestión de riesgo institucional',
    evidenciaNecesaria: 'Análisis de riesgos',
    demostracionSugerida:
      'Presentar matriz de riesgos con tratamiento y riesgo residual aceptado',
  },
  {
    controlId: 'GV-05',
    funcion: 'Gobernar',
    codigo: 'GV',
    tema: 'Gestión de cadena de suministro y terceros',
    evidenciaNecesaria: 'Análisis de dependencias',
    demostracionSugerida: 'Listar servidores/proveedores y su evaluación',
  },
  {
    controlId: 'GV-06',
    funcion: 'Gobernar',
    codigo: 'GV',
    tema: 'Marco de cumplimiento (MCU5, BCU, ISO, COBIT, URCDP)',
    evidenciaNecesaria: 'SoA + brecha MCU',
    demostracionSugerida:
      'Mostrar la SoA y la brecha por función con perfil Avanzado',
  },
  {
    controlId: 'GV-07',
    funcion: 'Gobernar',
    codigo: 'GV',
    tema: 'Presupuesto y recursos de seguridad',
    evidenciaNecesaria: 'Plan de inversión',
    demostracionSugerida: 'Presentar carta con dotación de recursos',
  },
  {
    controlId: 'GV-08',
    funcion: 'Gobernar',
    codigo: 'GV',
    tema: 'Revisión periódica de gobierno por la Dirección',
    evidenciaNecesaria: 'Actas de comité',
    demostracionSugerida: 'Mostrar actas de reuniones de seguimiento',
  },
  {
    controlId: 'ID-01',
    funcion: 'Identificar',
    codigo: 'ID',
    tema: 'Inventario de activos de información',
    evidenciaNecesaria: 'Registro de activos (Excel MCU)',
    demostracionSugerida:
      'Desplegar el Excel de activos completo y actualizado',
  },
  {
    controlId: 'ID-02',
    funcion: 'Identificar',
    codigo: 'ID',
    tema: 'Propietarios de activos y clasificación',
    evidenciaNecesaria: 'Registro de activos',
    demostracionSugerida: 'Mostrar que cada activo tiene dueño y clasificación',
  },
  {
    controlId: 'ID-03',
    funcion: 'Identificar',
    codigo: 'ID',
    tema: 'Análisis de impacto en el negocio (BIA)',
    evidenciaNecesaria: 'Matriz de criticidad',
    demostracionSugerida:
      'Presentar procesos críticos y activos que los soportan',
  },
  {
    controlId: 'ID-04',
    funcion: 'Identificar',
    codigo: 'ID',
    tema: 'Evaluación de riesgos de ciberseguridad',
    evidenciaNecesaria: 'Análisis de riesgos',
    demostracionSugerida: 'Presentar matriz 5x5 con tratamiento del riesgo',
  },
  {
    controlId: 'ID-05',
    funcion: 'Identificar',
    codigo: 'ID',
    tema: 'Comunicación y aceptación de riesgos',
    evidenciaNecesaria: 'Acta de aceptación',
    demostracionSugerida: 'Mostrar riesgo residual aceptado y firmado',
  },
  {
    controlId: 'ID-06',
    funcion: 'Identificar',
    codigo: 'ID',
    tema: 'Inventario de vulnerabilidades',
    evidenciaNecesaria: 'Registro de vulnerabilidades',
    demostracionSugerida: 'Desplegar el registro con CVSS y estado',
  },
  {
    controlId: 'ID-07',
    funcion: 'Identificar',
    codigo: 'ID',
    tema: 'Mapa de datos personales (URCDP)',
    evidenciaNecesaria: 'Registro de bases de datos',
    demostracionSugerida: 'Listar bases con datos personales y su tratamiento',
  },
  {
    controlId: 'ID-08',
    funcion: 'Identificar',
    codigo: 'ID',
    tema: 'Identificación de dependencias externas',
    evidenciaNecesaria: 'Diagrama de arquitectura',
    demostracionSugerida:
      'Mostrar servicios externos/integrados en el diagrama',
  },
  {
    controlId: 'PR-01',
    funcion: 'Proteger',
    codigo: 'PR',
    tema: 'Gestión de identidades y credenciales',
    evidenciaNecesaria: 'Configuración IAM',
    demostracionSugerida:
      'Demostrar alta/baja de usuarios y políticas de credenciales',
  },
  {
    controlId: 'PR-02',
    funcion: 'Proteger',
    codigo: 'PR',
    tema: 'Autenticación multifactor (TOTP/WebAuthn/Hello)',
    evidenciaNecesaria: 'Config. + capturas',
    demostracionSugerida: 'Registrar login con 2 factores en vivo',
  },
  {
    controlId: 'PR-03',
    funcion: 'Proteger',
    codigo: 'PR',
    tema: 'Revisión de privilegios (mínimo privilegio)',
    evidenciaNecesaria: 'Matriz de accesos',
    demostracionSugerida: 'Mostrar revisión periódica de privilegios',
  },
  {
    controlId: 'PR-04',
    funcion: 'Proteger',
    codigo: 'PR',
    tema: 'Protección de datos (cifrado en reposo y en tránsito)',
    evidenciaNecesaria: 'Cifrado de BD y TLS',
    demostracionSugerida: 'Demostrar cifrado de bóveda/BD y TLS 1.2+',
  },
  {
    controlId: 'PR-05',
    funcion: 'Proteger',
    codigo: 'PR',
    tema: 'Respaldos y prueba de restauración',
    evidenciaNecesaria: 'Registro de backup',
    demostracionSugerida: 'Restaurar un respaldo en vivo ante la auditoría',
  },
  {
    controlId: 'PR-06',
    funcion: 'Proteger',
    codigo: 'PR',
    tema: 'Capacitación y concientización del personal',
    evidenciaNecesaria: 'Plan de capacitación',
    demostracionSugerida: 'Presentar plan y registro de asistencia',
  },
  {
    controlId: 'PR-07',
    funcion: 'Proteger',
    codigo: 'PR',
    tema: 'Configuración segura de sistemas',
    evidenciaNecesaria: 'Config. endurecida',
    demostracionSugerida: 'Mostrar hardening por checklist',
  },
  {
    controlId: 'PR-08',
    funcion: 'Proteger',
    codigo: 'PR',
    tema: 'Mantenimiento y parcheo',
    evidenciaNecesaria: 'Historial de parches',
    demostracionSugerida: 'Mostrar aplicaciones de parches en el período',
  },
  {
    controlId: 'PR-09',
    funcion: 'Proteger',
    codigo: 'PR',
    tema: 'Protección de endpoints (HIDS/antivirus/EDR)',
    evidenciaNecesaria: 'Agentes activos',
    demostracionSugerida: 'Mostrar agentes HIDS conectados al SIEM',
  },
  {
    controlId: 'PR-10',
    funcion: 'Proteger',
    codigo: 'PR',
    tema: 'Protección de la red (firewalls, segmentación, IDS/IPS)',
    evidenciaNecesaria: 'Diagrama + reglas',
    demostracionSugerida: 'Presentar reglas de firewall y segmentación en vivo',
  },
  {
    controlId: 'PR-11',
    funcion: 'Proteger',
    codigo: 'PR',
    tema: 'Gestión de vulnerabilidades técnicas',
    evidenciaNecesaria: 'Escaneos + cierre',
    demostracionSugerida: 'Mostrar escaneos y resolución con plazos',
  },
  {
    controlId: 'PR-12',
    funcion: 'Proteger',
    codigo: 'PR',
    tema: 'Seguridad en el ciclo de desarrollo (SAST)',
    evidenciaNecesaria: 'Informe SAST',
    demostracionSugerida:
      'Mostrar informe de semgrep/bandit sin hallazgos críticos',
  },
  {
    controlId: 'DE-01',
    funcion: 'Detectar',
    codigo: 'DE',
    tema: 'Monitoreo continuo de la red (NIDS)',
    evidenciaNecesaria: 'Reglas Suricata/Zeek',
    demostracionSugerida: 'Mostrar eventos de red capturados recientemente',
  },
  {
    controlId: 'DE-02',
    funcion: 'Detectar',
    codigo: 'DE',
    tema: 'Monitoreo de hosts (HIDS/FIM)',
    evidenciaNecesaria: 'Alertas Wazuh',
    demostracionSugerida: 'Mostrar monitoreo de integridad de archivos',
  },
  {
    controlId: 'DE-03',
    funcion: 'Detectar',
    codigo: 'DE',
    tema: 'Correlación de eventos (SIEM)',
    evidenciaNecesaria: 'Dashboards SIEM',
    demostracionSugerida: 'Presentar dashboard con eventos correlacionados',
  },
  {
    controlId: 'DE-04',
    funcion: 'Detectar',
    codigo: 'DE',
    tema: 'Firmas y reglas de detección actualizadas',
    evidenciaNecesaria: 'Versión de firmas',
    demostracionSugerida: 'Mostrar fecha de actualización de firmas',
  },
  {
    controlId: 'DE-05',
    funcion: 'Detectar',
    codigo: 'DE',
    tema: 'Pruebas de detección (ejercicios púrpura/red team)',
    evidenciaNecesaria: 'Evidencia de simulación',
    demostracionSugerida: 'Presentar al menos un ataque simulado detectado',
  },
  {
    controlId: 'DE-06',
    funcion: 'Detectar',
    codigo: 'DE',
    tema: 'Detección de anomalías de comportamiento',
    evidenciaNecesaria: 'Regla de anomalía',
    demostracionSugerida: 'Mostrar una regla de comportamiento y su alerta',
  },
  {
    controlId: 'DE-07',
    funcion: 'Detectar',
    codigo: 'DE',
    tema: 'Alerta y notificación oportuna',
    evidenciaNecesaria: 'Canales de alerta',
    demostracionSugerida: 'Demostrar una alerta por mail/webhook/llamada',
  },
  {
    controlId: 'DE-08',
    funcion: 'Detectar',
    codigo: 'DE',
    tema: 'Monitoreo de los controles de protección',
    evidenciaNecesaria: 'Estado de controles',
    demostracionSugerida: 'Mostrar salud de firewalls/agentes en el dashboard',
  },
  {
    controlId: 'RS-01',
    funcion: 'Responder',
    codigo: 'RS',
    tema: 'Plan de respuesta a incidentes',
    evidenciaNecesaria: 'Procedimiento de incidentes',
    demostracionSugerida: 'Exponer el plan y sus fases',
  },
  {
    controlId: 'RS-02',
    funcion: 'Responder',
    codigo: 'RS',
    tema: 'Roles y comunicación en respuesta',
    evidenciaNecesaria: 'Matriz de comunicación',
    demostracionSugerida: 'Mostrar responsables de comunicación y escalamiento',
  },
  {
    controlId: 'RS-03',
    funcion: 'Responder',
    codigo: 'RS',
    tema: 'Análisis y contención de incidentes',
    evidenciaNecesaria: 'Registros de incidentes',
    demostracionSugerida:
      'Presentar un incidente completo (detección a cierre)',
  },
  {
    controlId: 'RS-04',
    funcion: 'Responder',
    codigo: 'RS',
    tema: 'Erradicación y recuperación',
    evidenciaNecesaria: 'Incidente resuelto',
    demostracionSugerida: 'Mostrar evidencia de la mitigación',
  },
  {
    controlId: 'RS-05',
    funcion: 'Responder',
    codigo: 'RS',
    tema: 'Notificación a autoridades (BCU, URCDP, CERTuy)',
    evidenciaNecesaria: 'Borradores de notificación',
    demostracionSugerida: 'Presentar notificación simulada completa',
  },
  {
    controlId: 'RS-06',
    funcion: 'Responder',
    codigo: 'RS',
    tema: 'Lecciones aprendidas y mejora',
    evidenciaNecesaria: 'Informe de lecciones',
    demostracionSugerida: 'Mostrar acciones correctivas aplicadas',
  },
  {
    controlId: 'RC-01',
    funcion: 'Recuperar',
    codigo: 'RC',
    tema: 'Plan de recuperación (BCP/DRP)',
    evidenciaNecesaria: 'Plan de continuidad',
    demostracionSugerida: 'Exponer el BCP/DRP con RTO/RPO',
  },
  {
    controlId: 'RC-02',
    funcion: 'Recuperar',
    codigo: 'RC',
    tema: 'Comunicación de crisis',
    evidenciaNecesaria: 'Procedimiento de crisis',
    demostracionSugerida: 'Presentar canales y responsables de crisis',
  },
  {
    controlId: 'RC-03',
    funcion: 'Recuperar',
    codigo: 'RC',
    tema: 'Restauración de respaldos validada',
    evidenciaNecesaria: 'Prueba de restauración',
    demostracionSugerida: 'Ejecutar/evidenciar una restauración real',
  },
  {
    controlId: 'RC-04',
    funcion: 'Recuperar',
    codigo: 'RC',
    tema: 'Reanudación de operaciones',
    evidenciaNecesaria: 'Plan de retorno',
    demostracionSugerida: 'Mostrar secuencia de reanudación de servicios',
  },
  {
    controlId: 'RC-05',
    funcion: 'Recuperar',
    codigo: 'RC',
    tema: 'Mejora continua post-recuperación',
    evidenciaNecesaria: 'Acciones de mejora',
    demostracionSugerida: 'Presentar mejoras aplicadas tras las simulaciones',
  },
] as const;
