import { useEffect, useMemo, useState } from 'react'
import { listarOrganizaciones, listarTrabajadores, listarUnidades } from '../../organizacion/api/organizacionApi'
import type { Organizacion, Trabajador, Unidad } from '../../organizacion/types/organizacion'
import { actualizarActivo, crearActivo, eliminarActivo, listarActivos, type Activo, type DatosActivo } from '../api/seguridadApi'
import '../seguridad.css'

export function ActivosPage() {
  const [organizaciones, setOrganizaciones] = useState<Organizacion[]>([]); const [organizacionId, setOrganizacionId] = useState(''); const [unidades, setUnidades] = useState<Unidad[]>([]); const [unidadId, setUnidadId] = useState(''); const [trabajadores, setTrabajadores] = useState<Trabajador[]>([]); const [activos, setActivos] = useState<Activo[]>([]); const [editando, setEditando] = useState<Activo | null>(null); const [nombre, setNombre] = useState(''); const [descripcion, setDescripcion] = useState(''); const [tipo, setTipo] = useState(''); const [criticidad, setCriticidad] = useState('MEDIA'); const [clasificacion, setClasificacion] = useState('INTERNO'); const [responsableId, setResponsableId] = useState(''); const [error, setError] = useState('')
  useEffect(() => { void Promise.all([listarOrganizaciones(new AbortController().signal), listarTrabajadores()]).then(([o, t]) => { setOrganizaciones(o); setOrganizacionId(o[0]?.id ?? ''); setTrabajadores(t) }).catch(() => setError('No se pudieron cargar los datos.')) }, [])
  useEffect(() => { if (!organizacionId) return; void Promise.resolve().then(() => { setUnidades([]); setUnidadId(''); setActivos([]); limpiar() }).then(() => listarUnidades(organizacionId, new AbortController().signal)).then((u) => { setUnidades(u); setUnidadId(u[0]?.id ?? '') }).catch(() => setError('No se pudieron cargar las unidades.')) }, [organizacionId])
  useEffect(() => { if (!unidadId) return; void listarActivos(unidadId).then(setActivos).catch(() => setError('No se pudieron cargar los activos.')) }, [unidadId])
  const trabajadoresVisibles = useMemo(() => trabajadores.filter((t) => unidades.some((u) => u.id === t.unidadOrganizativa?.id)), [trabajadores, unidades])
  function limpiar() { setEditando(null); setNombre(''); setDescripcion(''); setTipo(''); setCriticidad('MEDIA'); setClasificacion('INTERNO'); setResponsableId('') }
  function editar(a: Activo) { setEditando(a); setUnidadId(a.unidadOrganizativa.id); setNombre(a.nombre); setDescripcion(a.descripcion ?? ''); setTipo(a.tipo); setCriticidad(a.criticidad); setClasificacion(a.clasificacion); setResponsableId(a.responsable?.id ?? '') }
  async function guardar(e: React.FormEvent) { e.preventDefault(); if (!unidadId || !nombre.trim() || !tipo.trim()) return; const d: DatosActivo = { nombre: nombre.trim(), descripcion: descripcion.trim(), tipo: tipo.trim(), criticidad, clasificacion, ...(responsableId && { responsableId }) }; try { if (editando) await actualizarActivo(editando.id, d); else await crearActivo(unidadId, d); setActivos(await listarActivos(unidadId)); limpiar() } catch { setError('No se pudo guardar el activo.') } }
  async function borrar(a: Activo) { if (!window.confirm(`¿Eliminar el activo “${a.nombre}”?`)) return; try { await eliminarActivo(a.id); setActivos(await listarActivos(unidadId)) } catch { setError('No se pudo eliminar el activo.') } }
  return <div className="aplicacion"><header className="barra-superior"><span className="marca"><span className="marca-simbolo">R</span><span className="marca-texto"><strong>RSI</strong><small>Gestión integrada</small></span></span><span className="entorno">Sistema de gestión</span></header><main className="contenido"><div className="encabezado-pagina"><div><p className="sobretitulo">SEGURIDAD</p><h1>Inventario de activos</h1><p className="introduccion">Registrá los activos de cada unidad organizativa.</p></div><label className="selector-organizacion"><span>Organización</span><select value={organizacionId} onChange={(e) => setOrganizacionId(e.target.value)}>{organizaciones.map((o) => <option key={o.id} value={o.id}>{o.nombre}</option>)}</select></label></div>{error && <p className="mensaje mensaje-error">{error}</p>}<section className="panel-estructura"><label className="selector-organizacion"> <span>Unidad organizativa</span><select value={unidadId} onChange={(e) => setUnidadId(e.target.value)}>{unidades.map((u) => <option key={u.id} value={u.id}>{u.nombre}</option>)}</select></label><form className="formulario-activo" onSubmit={guardar}><h3>{editando ? 'Editar activo' : 'Nuevo activo'}</h3><label>Nombre<input value={nombre} onChange={(e) => setNombre(e.target.value)} required /></label><label>Tipo<input value={tipo} onChange={(e) => setTipo(e.target.value)} placeholder="Servidor, aplicación…" required /></label><label>Criticidad<select value={criticidad} onChange={(e) => setCriticidad(e.target.value)}><option>BAJA</option><option>MEDIA</option><option>ALTA</option><option>CRITICA</option></select></label><label>Clasificación<input value={clasificacion} onChange={(e) => setClasificacion(e.target.value)} required /></label><label>Responsable<select value={responsableId} onChange={(e) => setResponsableId(e.target.value)}><option value="">Sin responsable</option>{trabajadoresVisibles.map((t) => <option key={t.id} value={t.id}>{t.nombre}</option>)}</select></label><label className="campo-ancho">Descripción<textarea value={descripcion} onChange={(e) => setDescripcion(e.target.value)} rows={2} /></label><div className="formulario-acciones"><button type="submit">{editando ? 'Guardar cambios' : 'Crear activo'}</button>{editando && <button type="button" onClick={limpiar}>Cancelar</button>}</div></form><div className="lista-trabajadores">{activos.map((a) => <article className="unidad-tarjeta" key={a.id}><div className="unidad-detalle"><span className="unidad-tipo">{a.tipo} · {a.criticidad}</span><h3>{a.nombre}</h3><p>{a.descripcion || 'Sin descripción'} · Responsable: {a.responsable?.nombre ?? 'Sin responsable'}</p></div><div className="unidad-acciones"><button type="button" onClick={() => editar(a)}>Editar</button><button type="button" onClick={() => void borrar(a)}>Eliminar</button></div></article>)}</div></section></main></div>
}
