import { useEffect, useMemo, useState } from 'react'
import { listarOrganizaciones, listarTrabajadores, listarUnidades } from '../../organizacion/api/organizacionApi'
import type { Organizacion, Trabajador, Unidad } from '../../organizacion/types/organizacion'
import { actualizarIncidente, crearIncidente, eliminarIncidente, listarActivos, listarIncidentes, type Activo, type DatosIncidente, type Incidente } from '../api/seguridadApi'
import '../seguridad.css'

export function IncidentesPage() {
  const [organizaciones, setOrganizaciones] = useState<Organizacion[]>([]); const [organizacionId, setOrganizacionId] = useState(''); const [unidades, setUnidades] = useState<Unidad[]>([]); const [activos, setActivos] = useState<Activo[]>([]); const [trabajadores, setTrabajadores] = useState<Trabajador[]>([]); const [incidentes, setIncidentes] = useState<Incidente[]>([]); const [editando, setEditando] = useState<Incidente | null>(null); const [activoId, setActivoId] = useState(''); const [titulo, setTitulo] = useState(''); const [descripcion, setDescripcion] = useState(''); const [severidad, setSeveridad] = useState('MEDIA'); const [estado, setEstado] = useState('ABIERTO'); const [lecciones, setLecciones] = useState(''); const [responsableId, setResponsableId] = useState(''); const [error, setError] = useState('')
  useEffect(() => { void Promise.all([listarOrganizaciones(new AbortController().signal), listarTrabajadores(), listarActivos(), listarIncidentes()]).then(([o, t, a, i]) => { setOrganizaciones(o); setOrganizacionId(o[0]?.id ?? ''); setTrabajadores(t); setActivos(a); setIncidentes(i) }).catch(() => setError('No se pudieron cargar los datos.')) }, [])
  useEffect(() => { if (organizacionId) void listarUnidades(organizacionId, new AbortController().signal).then(setUnidades).catch(() => setError('No se pudieron cargar las unidades.')) }, [organizacionId])
  const ids = useMemo(() => new Set(unidades.map((u) => u.id)), [unidades]); const activosVisibles = activos.filter((a) => ids.has(a.unidadOrganizativa.id)); const incidentesVisibles = incidentes.filter((i) => activosVisibles.some((a) => a.id === i.activoId)); const trabajadoresVisibles = trabajadores.filter((t) => ids.has(t.unidadOrganizativa?.id ?? ''))
  function limpiar() { setEditando(null); setActivoId(''); setTitulo(''); setDescripcion(''); setSeveridad('MEDIA'); setEstado('ABIERTO'); setLecciones(''); setResponsableId('') }
  function editar(i: Incidente) { setEditando(i); setActivoId(i.activoId); setTitulo(i.titulo); setDescripcion(i.descripcion ?? ''); setSeveridad(i.severidad); setEstado(i.estado); setLecciones(i.leccionesAprendidas ?? ''); setResponsableId(i.responsable?.id ?? '') }
  async function guardar(e: React.FormEvent) { e.preventDefault(); if (!activoId || !titulo.trim() || !severidad.trim()) return; const d: DatosIncidente = { activoId, titulo: titulo.trim(), descripcion: descripcion.trim(), severidad, estado, leccionesAprendidas: lecciones.trim(), ...(responsableId && { responsableId }) }; try { if (editando) await actualizarIncidente(editando.id, d); else await crearIncidente(d); setIncidentes(await listarIncidentes()); limpiar() } catch { setError('No se pudo guardar el incidente.') } }
  async function borrar(i: Incidente) { if (!window.confirm(`¿Eliminar el incidente “${i.titulo}”?`)) return; try { await eliminarIncidente(i.id); setIncidentes(await listarIncidentes()) } catch { setError('No se pudo eliminar el incidente.') } }
  return <div className="aplicacion"><header className="barra-superior"><span className="marca"><span className="marca-simbolo">R</span><span className="marca-texto"><strong>RSI</strong><small>Gestión integrada</small></span></span><span className="entorno">Sistema de gestión</span></header><main className="contenido"><div className="encabezado-pagina"><div><p className="sobretitulo">SEGURIDAD</p><h1>Incidentes</h1><p className="introduccion">Registrá y gestioná incidentes asociados a los activos.</p></div><label className="selector-organizacion"><span>Organización</span><select value={organizacionId} onChange={(e) => setOrganizacionId(e.target.value)}>{organizaciones.map((o) => <option key={o.id} value={o.id}>{o.nombre}</option>)}</select></label></div>{error && <p className="mensaje mensaje-error">{error}</p>}<section className="panel-estructura"><form className="formulario-incidente" onSubmit={guardar}><h3>{editando ? 'Editar incidente' : 'Nuevo incidente'}</h3><label>Activo<select value={activoId} onChange={(e) => setActivoId(e.target.value)} required><option value="">Seleccioná un activo</option>{activosVisibles.map((a) => <option key={a.id} value={a.id}>{a.nombre}</option>)}</select></label><label>Título<input value={titulo} onChange={(e) => setTitulo(e.target.value)} required /></label><label>Severidad<select value={severidad} onChange={(e) => setSeveridad(e.target.value)}><option>BAJA</option><option>MEDIA</option><option>ALTA</option><option>CRITICA</option></select></label><label>Estado<select value={estado} onChange={(e) => setEstado(e.target.value)}><option>ABIERTO</option><option>EN_TRATAMIENTO</option><option>CERRADO</option></select></label><label>Responsable<select value={responsableId} onChange={(e) => setResponsableId(e.target.value)}><option value="">Sin responsable</option>{trabajadoresVisibles.map((t) => <option key={t.id} value={t.id}>{t.nombre}</option>)}</select></label><label className="campo-ancho">Descripción<textarea value={descripcion} onChange={(e) => setDescripcion(e.target.value)} rows={2} /></label><label className="campo-ancho">Lecciones aprendidas<textarea value={lecciones} onChange={(e) => setLecciones(e.target.value)} rows={2} /></label><div className="formulario-acciones"><button type="submit">{editando ? 'Guardar cambios' : 'Crear incidente'}</button>{editando && <button type="button" onClick={limpiar}>Cancelar</button>}</div></form><div className="lista-trabajadores">{incidentesVisibles.map((i) => <article className="unidad-tarjeta" key={i.id}><div className="unidad-detalle"><span className="unidad-tipo">{i.severidad} · {i.estado}</span><h3>{i.titulo}</h3><p>{i.activo.nombre} · Responsable: {i.responsable?.nombre ?? 'Sin responsable'}</p></div><div className="unidad-acciones"><button type="button" onClick={() => editar(i)}>Editar</button><button type="button" onClick={() => void borrar(i)}>Eliminar</button></div></article>)}</div></section></main></div>
}
