import { useEffect, useMemo, useState } from 'react'
import { actualizarProceso, crearProceso, eliminarProceso, listarOrganizaciones, listarProcesos, listarTrabajadores } from '../api/organizacionApi'
import type { Organizacion, Trabajador } from '../types/organizacion'
import type { DatosProceso, Proceso } from '../api/organizacionApi'
import '../organizacion.css'

export function ProcesosPage() {
  const [organizaciones, setOrganizaciones] = useState<Organizacion[]>([]); const [organizacionId, setOrganizacionId] = useState('')
  const [procesos, setProcesos] = useState<Proceso[]>([]); const [trabajadores, setTrabajadores] = useState<Trabajador[]>([]); const [editando, setEditando] = useState<Proceso | null>(null)
  const [nombre, setNombre] = useState(''); const [descripcion, setDescripcion] = useState(''); const [estado, setEstado] = useState('BORRADOR'); const [version, setVersion] = useState('1.0'); const [responsableId, setResponsableId] = useState(''); const [error, setError] = useState('')
  useEffect(() => { void Promise.all([listarOrganizaciones(new AbortController().signal), listarProcesos(), listarTrabajadores()]).then(([o, p, t]) => { setOrganizaciones(o); setOrganizacionId(o[0]?.id ?? ''); setProcesos(p); setTrabajadores(t) }).catch(() => setError('No se pudieron cargar los datos.')) }, [])
  const visibles = useMemo(() => procesos.filter((p) => p.organizacionId === organizacionId), [procesos, organizacionId])
  function limpiar() { setEditando(null); setNombre(''); setDescripcion(''); setEstado('BORRADOR'); setVersion('1.0'); setResponsableId('') }
  function editar(p: Proceso) { setEditando(p); setNombre(p.nombre); setDescripcion(p.descripcion ?? ''); setEstado(p.estado); setVersion(p.version); setResponsableId(p.responsable?.id ?? '') }
  async function guardar(e: React.FormEvent) { e.preventDefault(); if (!organizacionId || !nombre.trim()) return; const d: DatosProceso = { nombre: nombre.trim(), descripcion: descripcion.trim(), estado, version, ...(responsableId && { responsableId }) }; try { if (editando) await actualizarProceso(editando.id, d); else await crearProceso(organizacionId, d); setProcesos(await listarProcesos()); limpiar() } catch { setError('No se pudo guardar el proceso.') } }
  async function borrar(p: Proceso) { if (!window.confirm(`¿Eliminar el proceso “${p.nombre}”?`)) return; try { await eliminarProceso(p.id); setProcesos(await listarProcesos()) } catch { setError('No se pudo eliminar el proceso.') } }
  return <div className="aplicacion"><header className="barra-superior"><span className="marca"><span className="marca-simbolo">R</span><span className="marca-texto"><strong>RSI</strong><small>Gestión integrada</small></span></span><span className="entorno">Sistema de gestión</span></header><main className="contenido"><div className="encabezado-pagina"><div><p className="sobretitulo">ORGANIZACIÓN</p><h1>Procesos</h1><p className="introduccion">Registrá los procesos de la organización y su responsable.</p></div><label className="selector-organizacion"><span>Organización</span><select value={organizacionId} onChange={(e) => setOrganizacionId(e.target.value)}>{organizaciones.map((o) => <option key={o.id} value={o.id}>{o.nombre}</option>)}</select></label></div>{error && <p className="mensaje mensaje-error">{error}</p>}<section className="panel-estructura"><form className="formulario-proceso" onSubmit={guardar}><h3>{editando ? 'Editar proceso' : 'Nuevo proceso'}</h3><label>Nombre<input value={nombre} onChange={(e) => setNombre(e.target.value)} required /></label><label>Versión<input value={version} onChange={(e) => setVersion(e.target.value)} /></label><label>Estado<select value={estado} onChange={(e) => setEstado(e.target.value)}><option>BORRADOR</option><option>ACTIVO</option><option>INACTIVO</option></select></label><label>Responsable<select value={responsableId} onChange={(e) => setResponsableId(e.target.value)}><option value="">Sin responsable</option>{trabajadores.map((t) => <option key={t.id} value={t.id}>{t.nombre} · {t.cargo}</option>)}</select></label><label className="campo-ancho">Descripción<textarea value={descripcion} onChange={(e) => setDescripcion(e.target.value)} rows={3} /></label><div className="formulario-acciones"><button type="submit">{editando ? 'Guardar cambios' : 'Crear proceso'}</button>{editando && <button type="button" onClick={limpiar}>Cancelar</button>}</div></form><div className="lista-trabajadores">{visibles.map((p) => <article className="unidad-tarjeta" key={p.id}><div className="unidad-detalle"><span className="unidad-tipo">{p.estado} · v{p.version}</span><h3>{p.nombre}</h3><p>{p.descripcion || 'Sin descripción'} · Responsable: {p.responsable?.nombre ?? 'Sin responsable'}</p></div><div className="unidad-acciones"><button type="button" onClick={() => editar(p)}>Editar</button><button type="button" onClick={() => void borrar(p)}>Eliminar</button></div></article>)}</div></section></main></div>
}
