import { notificarGuardado } from '../../../shared/notificar'
import { PageHeader } from '../../../shared/PageHeader'
import { Asistente } from '../../../shared/Asistente'
import { Badge } from '../../../shared/Badge'
import { Listado } from '../../../shared/Listado'
import { useEffect, useMemo, useState } from 'react'
import { crearAsignacionRaci, eliminarAsignacionRaci, listarAsignacionesRaci, listarOrganizaciones, listarProcesos, listarTrabajadores, type AsignacionRaci, type Proceso, type TipoRaci } from '../api/organizacionApi'
import type { Organizacion, Trabajador } from '../types/organizacion'
import '../organizacion.css'

const nombres: Record<TipoRaci, string> = { R: 'Responsable', A: 'Aprobador', C: 'Consultado', I: 'Informado' }
export function RaciPage() {
  const [cargandoListado, setCargandoListado] = useState(true)

  const [asistenteAbierto, setAsistenteAbierto] = useState(false)

  const [organizaciones, setOrganizaciones] = useState<Organizacion[]>([]); const [organizacionId, setOrganizacionId] = useState(''); const [procesos, setProcesos] = useState<Proceso[]>([]); const [trabajadores, setTrabajadores] = useState<Trabajador[]>([]); const [asignaciones, setAsignaciones] = useState<AsignacionRaci[]>([]); const [procesoId, setProcesoId] = useState(''); const [trabajadorId, setTrabajadorId] = useState(''); const [tipo, setTipo] = useState<TipoRaci>('R'); const [error, setError] = useState('')
  useEffect(() => { void Promise.all([listarOrganizaciones(new AbortController().signal), listarProcesos(), listarTrabajadores(), listarAsignacionesRaci()]).then(([o, p, t, a]) => { setOrganizaciones(o); setOrganizacionId(o[0]?.id ?? ''); setProcesos(p); setTrabajadores(t); setAsignaciones(a) }).catch(() => setError('No se pudieron cargar los datos.')).finally(() => setCargandoListado(false)) }, [])
  const visibles = useMemo(() => asignaciones.filter((a) => a.proceso.organizacionId === organizacionId), [asignaciones, organizacionId]); const procesosVisibles = procesos.filter((p) => p.organizacionId === organizacionId); const porProceso = procesosVisibles.map((p) => ({ proceso: p, asignaciones: visibles.filter((a) => a.procesoId === p.id) }))
  async function guardar(e: React.FormEvent) { e.preventDefault(); if (!procesoId || !trabajadorId) return; try { await crearAsignacionRaci({ procesoId, trabajadorId, tipoResponsabilidad: tipo }); setAsignaciones(await listarAsignacionesRaci()); notificarGuardado(); setAsistenteAbierto(false) } catch { setError('No se pudo crear la asignación RACI.') } }
  async function borrar(a: AsignacionRaci) { if (!window.confirm('¿Eliminar esta asignación RACI?')) return; try { await eliminarAsignacionRaci(a.id); setAsignaciones(await listarAsignacionesRaci()) } catch { setError('No se pudo eliminar la asignación.') } }
  return <div className="aplicacion"><main className="contenido"><PageHeader categoria="ORGANIZACIÓN" titulo="Asignaciones RACI" descripcion="Definí qué responsabilidad tiene cada trabajador en un proceso."><label className="selector-organizacion"><span>Organización</span><select value={organizacionId} onChange={(e) => setOrganizacionId(e.target.value)}>{organizaciones.map((o) => <option key={o.id} value={o.id}>{o.nombre}</option>)}</select></label><div className="asistente-lanzador"><button className="boton-principal" type="button" onClick={() => { setProcesoId(''); setTrabajadorId(''); setTipo('R'); setError(''); setAsistenteAbierto(true) }}>＋ Nueva asignación</button></div></PageHeader>{error && <p className="mensaje mensaje-error" role="alert">{error}</p>}<section className="panel-estructura"><Asistente abierto={asistenteAbierto} titulo={"Nueva asignación"} error={error} alCerrar={() => setAsistenteAbierto(false)}><form className="formulario-raci" onSubmit={guardar}><h3>Nueva asignación</h3><label>Proceso<select value={procesoId} onChange={(e) => setProcesoId(e.target.value)} required><option value="">Seleccioná un proceso</option>{procesosVisibles.map((p) => <option key={p.id} value={p.id}>{p.nombre}</option>)}</select></label><label>Trabajador<select value={trabajadorId} onChange={(e) => setTrabajadorId(e.target.value)} required><option value="">Seleccioná un trabajador</option>{trabajadores.map((t) => <option key={t.id} value={t.id}>{t.nombre} · {t.cargo}</option>)}</select></label><label>Responsabilidad<select value={tipo} onChange={(e) => setTipo(e.target.value as TipoRaci)}>{Object.entries(nombres).map(([valor, nombre]) => <option key={valor} value={valor}>{valor} — {nombre}</option>)}</select></label><button type="submit">Asignar</button></form></Asistente><Listado cargando={cargandoListado}>{porProceso.map(({ proceso, asignaciones: delProceso }) => <article className="proceso-raci" key={proceso.id}><div className="proceso-raci-encabezado"><div><Badge>PROCESO</Badge><h3>{proceso.nombre}</h3></div><span>{delProceso.length} asignaciones</span></div>{delProceso.length === 0 ? <p className="mensaje">Sin asignaciones RACI.</p> : <div className="lista-registros">{delProceso.map((a) => <div className="unidad-tarjeta" key={a.id}><div className="unidad-detalle"><Badge>{a.tipoResponsabilidad} · {nombres[a.tipoResponsabilidad]}</Badge><p>{a.trabajador.nombre} · {a.trabajador.cargo}</p></div><button className="boton-destructivo" type="button" onClick={() => void borrar(a)}>Eliminar</button></div>)}</div>}</article>)}</Listado></section></main></div>
}
