import { notificarGuardado } from '../../../shared/notificar'
import { PageHeader } from '../../../shared/PageHeader'
import { Asistente } from '../../../shared/Asistente'
import { useEffect, useState } from 'react'
import { listarOrganizaciones } from '../../organizacion/api/organizacionApi'
import type { Organizacion } from '../../organizacion/types/organizacion'
import { listarEvidencias, type Evidencia } from '../api/evidenciasApi'
import { guardarEvaluacionSoa, listarControlesSoa, type SoaControl } from '../api/soaApi'
import '../cumplimiento.css'

export function EvaluacionSoaPage() {
 const [asistenteAbierto, setAsistenteAbierto] = useState(false)
  const [organizaciones, setOrganizaciones] = useState<Organizacion[]>([]); const [organizacionId, setOrganizacionId] = useState(''); const [controles, setControles] = useState<SoaControl[]>([]); const [evidencias, setEvidencias] = useState<Evidencia[]>([]); const [seleccionado, setSeleccionado] = useState(''); const [aplica, setAplica] = useState(''); const [justificacion, setJustificacion] = useState(''); const [insumos, setInsumos] = useState(''); const [estado, setEstado] = useState('PENDIENTE'); const [evidenciaId, setEvidenciaId] = useState(''); const [error, setError] = useState(''); const [guardando, setGuardando] = useState(false)
  const control = controles.find(c => c.controlId === seleccionado)
  const evidenciasVisibles = evidencias.filter(e => e.organizacionId === organizacionId)
  useEffect(() => { void listarOrganizaciones(new AbortController().signal).then(async o => { setOrganizaciones(o); const id = o[0]?.id ?? ''; setOrganizacionId(id); if (id) { setControles(await listarControlesSoa(id)); setEvidencias(await listarEvidencias()) } }).catch(() => setError('No se pudieron cargar los datos.')) }, [])
  useEffect(() => { if (!organizacionId) return; void listarControlesSoa(organizacionId).then(setControles).catch(() => setError('No se pudieron cargar los controles SOA.')) }, [organizacionId])
  function seleccionar(id: string) { setError(''); setAsistenteAbierto(true); const evaluacion = controles.find(c => c.controlId === id)?.evaluacion; setSeleccionado(id); setAplica(evaluacion?.aplica === null || evaluacion?.aplica === undefined ? '' : String(evaluacion.aplica)); setJustificacion(evaluacion?.justificacion ?? ''); setInsumos(evaluacion?.insumos ?? ''); setEstado(evaluacion?.estado ?? 'PENDIENTE'); setEvidenciaId(evaluacion?.evidenciaId ?? '') }
  async function guardar(evento: React.FormEvent) { evento.preventDefault(); if (!organizacionId || !seleccionado) return; setGuardando(true); setError(''); try { await guardarEvaluacionSoa(organizacionId, seleccionado, { aplica: aplica === '' ? null : aplica === 'true', justificacion, insumos, estado, ...(evidenciaId && { evidenciaId }) }); setControles(await listarControlesSoa(organizacionId)); notificarGuardado(); setAsistenteAbierto(false) } catch { setError('No se pudo guardar la evaluación SOA.') } finally { setGuardando(false) } }
  return <div className="aplicacion"><main className="contenido"><PageHeader categoria="CUMPLIMIENTO" titulo="Evaluación SOA" descripcion="Registrá la aplicabilidad y el estado de cada control para la organización."><label className="selector-organizacion"><span>Organización</span><select value={organizacionId} onChange={e => setOrganizacionId(e.target.value)}>{organizaciones.map(o => <option key={o.id} value={o.id}>{o.nombre}</option>)}</select></label></PageHeader>{error && <p className="mensaje mensaje-error" role="alert">{error}</p>}<section className="panel-estructura"><div className="soa-lista">{controles.map(c => <button className={c.controlId === seleccionado ? 'soa-control seleccionado' : 'soa-control'} type="button" key={c.controlId} onClick={() => seleccionar(c.controlId)}><strong>{c.controlId}</strong><span>{c.tema}</span><small>{c.evaluacion?.estado ?? 'Sin evaluar'}</small></button>)}</div>{control && <Asistente abierto={asistenteAbierto} titulo={control.controlId + ' — ' + control.tema} error={error} alCerrar={() => setAsistenteAbierto(false)}><form className="formulario-cumplimiento soa-formulario" onSubmit={guardar}><h3>{control.controlId} — {control.tema}</h3><label>¿Aplica?<select value={aplica} onChange={e => setAplica(e.target.value)}><option value="">Pendiente</option><option value="true">Sí</option><option value="false">No</option></select></label><label>Estado<select value={estado} onChange={e => setEstado(e.target.value)}><option>PENDIENTE</option><option>EN_IMPLEMENTACION</option><option>IMPLEMENTADO</option><option>NO_APLICA</option></select></label><label className="campo-ancho">Justificación para la organización<textarea value={justificacion} onChange={e => setJustificacion(e.target.value)} required={aplica !== ''} rows={3} /></label><label className="campo-ancho">Insumos organizacionales<textarea value={insumos} onChange={e => setInsumos(e.target.value)} rows={3} /></label><label className="campo-ancho">Evidencia vinculada<select value={evidenciaId} onChange={e => setEvidenciaId(e.target.value)}><option value="">Sin evidencia</option>{evidenciasVisibles.map(e => <option key={e.id} value={e.id}>{e.nombre}</option>)}</select></label><div className="formulario-acciones"><button type="submit" disabled={guardando}>{guardando ? 'Guardando…' : 'Guardar evaluación'}</button></div></form></Asistente>}</section></main></div>
}
