import { useEffect, useMemo, useState } from 'react'
import { listarOrganizaciones, listarTrabajadores } from '../../organizacion/api/organizacionApi'
import type { Organizacion, Trabajador } from '../../organizacion/types/organizacion'
import { actualizarEvidencia, crearEvidencia, eliminarEvidencia, listarEvidencias, type DatosEvidencia, type Evidencia } from '../api/evidenciasApi'
import { listarPoliticas, type Politica } from '../api/cumplimientoApi'
import '../cumplimiento.css'

export function EvidenciasPage() {
  const [organizaciones, setOrganizaciones] = useState<Organizacion[]>([]); const [organizacionId, setOrganizacionId] = useState(''); const [trabajadores, setTrabajadores] = useState<Trabajador[]>([]); const [politicas, setPoliticas] = useState<Politica[]>([]); const [evidencias, setEvidencias] = useState<Evidencia[]>([]); const [editando, setEditando] = useState<Evidencia | null>(null); const [nombre, setNombre] = useState(''); const [descripcion, setDescripcion] = useState(''); const [tipo, setTipo] = useState('DOCUMENTO'); const [ubicacion, setUbicacion] = useState(''); const [responsableId, setResponsableId] = useState(''); const [politicaId, setPoliticaId] = useState(''); const [error, setError] = useState('')
  useEffect(() => { void Promise.all([listarOrganizaciones(new AbortController().signal), listarTrabajadores(), listarPoliticas(), listarEvidencias()]).then(([o, t, p, e]) => { setOrganizaciones(o); setOrganizacionId(o[0]?.id ?? ''); setTrabajadores(t); setPoliticas(p); setEvidencias(e) }).catch(() => setError('No se pudieron cargar los datos.')) }, [])
  const visibles = useMemo(() => evidencias.filter((e) => e.organizacionId === organizacionId), [evidencias, organizacionId]); const trabajadoresVisibles = trabajadores.filter((t) => t.unidadOrganizativa?.organizacionId === organizacionId); const politicasVisibles = politicas.filter((p) => p.organizacionId === organizacionId)
  function limpiar() { setEditando(null); setNombre(''); setDescripcion(''); setTipo('DOCUMENTO'); setUbicacion(''); setResponsableId(''); setPoliticaId('') }
  function editar(e: Evidencia) { setEditando(e); setNombre(e.nombre); setDescripcion(e.descripcion ?? ''); setTipo(e.tipo); setUbicacion(e.ubicacion ?? ''); setResponsableId(e.responsable?.id ?? ''); setPoliticaId(e.politica?.id ?? '') }
  async function guardar(evento: React.FormEvent) { evento.preventDefault(); if (!organizacionId || !nombre.trim() || !tipo.trim()) return; const datos: DatosEvidencia = { nombre: nombre.trim(), descripcion: descripcion.trim(), tipo, ubicacion: ubicacion.trim(), ...(responsableId && { responsableId }), ...(politicaId && { politicaId }) }; try { if (editando) await actualizarEvidencia(editando.id, datos); else await crearEvidencia(organizacionId, datos); setEvidencias(await listarEvidencias()); limpiar() } catch { setError('No se pudo guardar la evidencia.') } }
  async function borrar(e: Evidencia) { if (!window.confirm(`¿Eliminar la evidencia “${e.nombre}”?`)) return; try { await eliminarEvidencia(e.id); setEvidencias(await listarEvidencias()) } catch { setError('No se pudo eliminar la evidencia.') } }
  return <div className="aplicacion"><header className="barra-superior"><span className="marca"><span className="marca-simbolo">R</span><span className="marca-texto"><strong>RSI</strong><small>Gestión integrada</small></span></span><span className="entorno">Sistema de gestión</span></header><main className="contenido"><div className="encabezado-pagina"><div><p className="sobretitulo">CUMPLIMIENTO</p><h1>Evidencias</h1><p className="introduccion">Registrá evidencias de la organización seleccionada.</p></div><label className="selector-organizacion"><span>Organización</span><select value={organizacionId} onChange={(e) => setOrganizacionId(e.target.value)}>{organizaciones.map((o) => <option key={o.id} value={o.id}>{o.nombre}</option>)}</select></label></div>{error && <p className="mensaje mensaje-error">{error}</p>}<section className="panel-estructura"><form className="formulario-cumplimiento" onSubmit={guardar}><h3>{editando ? 'Editar evidencia' : 'Nueva evidencia'}</h3><label>Nombre<input value={nombre} onChange={(e) => setNombre(e.target.value)} required /></label><label>Tipo<input value={tipo} onChange={(e) => setTipo(e.target.value)} required /></label><label>Ubicación<input value={ubicacion} onChange={(e) => setUbicacion(e.target.value)} /></label><label>Responsable<select value={responsableId} onChange={(e) => setResponsableId(e.target.value)}><option value="">Sin responsable</option>{trabajadoresVisibles.map((t) => <option key={t.id} value={t.id}>{t.nombre}</option>)}</select></label><label>Política<select value={politicaId} onChange={(e) => setPoliticaId(e.target.value)}><option value="">Sin política asociada</option>{politicasVisibles.map((p) => <option key={p.id} value={p.id}>{p.titulo}</option>)}</select></label><label className="campo-ancho">Descripción<textarea value={descripcion} onChange={(e) => setDescripcion(e.target.value)} rows={3} /></label><div className="formulario-acciones"><button type="submit">{editando ? 'Guardar cambios' : 'Crear evidencia'}</button>{editando && <button type="button" onClick={limpiar}>Cancelar</button>}</div></form><div className="lista-cumplimiento">{visibles.map((e) => <article className="unidad-tarjeta" key={e.id}><div className="unidad-detalle"><span className="unidad-tipo">{e.tipo}</span><h3>{e.nombre}</h3><p>{e.descripcion || 'Sin descripción'} · Responsable: {e.responsable?.nombre ?? 'Sin responsable'}</p></div><div className="unidad-acciones"><button type="button" onClick={() => editar(e)}>Editar</button><button type="button" onClick={() => void borrar(e)}>Eliminar</button></div></article>)}</div></section></main></div>
}
