import { PageHeader } from '../../../shared/PageHeader'
import { useEffect, useState } from 'react'
import { listarOrganizaciones } from '../../organizacion/api/organizacionApi'
import type { Organizacion } from '../../organizacion/types/organizacion'
import { exportarBrechas, exportarControlesSoa, exportarInventario, exportarSoa } from '../api/exportacionesApi'
import '../cumplimiento.css'
function descargar(nombre: string, contenido: string, tipo: string) { const enlace = document.createElement('a'); enlace.href = URL.createObjectURL(new Blob([contenido], { type: tipo })); enlace.download = nombre; enlace.click(); URL.revokeObjectURL(enlace.href) }

function vistaPrevia(contenido: string) { const lineas=contenido.split('\n'); const elementos=[]; for(let i=0;i<lineas.length;i++){const linea=lineas[i]; if(linea.startsWith('|')&&!linea.startsWith('|---')){const filas=[]; while(i<lineas.length&&lineas[i].startsWith('|')){if(!lineas[i].startsWith('|---')) filas.push(lineas[i].split('|').filter(Boolean).map(celda=>celda.trim())); i++} i--; elementos.push(<div className="tabla-exportacion" key={i}><table><thead><tr>{filas[0]?.map((celda,j)=><th key={j}>{celda}</th>)}</tr></thead><tbody>{filas.slice(1).map((fila,j)=><tr key={j}>{fila.map((celda,k)=><td key={k}>{celda}</td>)}</tr>)}</tbody></table></div>)} else if(linea.startsWith('# ')) elementos.push(<h2 key={i}>{linea.slice(2)}</h2>); else if(linea.startsWith('## ')) elementos.push(<h3 key={i}>{linea.slice(3)}</h3>); else if(linea.trim()) elementos.push(<p key={i}>{linea}</p>)} return elementos }

export function ExportacionesPage() { const [orgs,setOrgs]=useState<Organizacion[]>([]); const [orgId,setOrgId]=useState(''); const [resultado,setResultado]=useState(''); const [error,setError]=useState(''); const [cargando,setCargando]=useState(false); useEffect(()=>{void listarOrganizaciones(new AbortController().signal).then(o=>{setOrgs(o);setOrgId(o[0]?.id??'')}).catch(()=>setError('No se pudieron cargar las organizaciones.'))},[]); async function ejecutar(nombre:string, accion:()=>Promise<{contenido:string}>){setCargando(true);setError('');try{setResultado((await accion()).contenido)}catch{setError(`No se pudo generar ${nombre}.`)}finally{setCargando(false)}} const descargarCsv=()=>{const filas=resultado.split('\n').filter(linea=>linea.startsWith('|')&&!linea.startsWith('|---')).map(linea=>linea.split('|').filter(Boolean).map(celda=>`"${celda.trim().replaceAll('"','""')}"`).join(',')); if(filas.length) descargar('inventario-activos.csv',filas.join('\n'),'text/csv;charset=utf-8')}; return <div className="aplicacion"><main className="contenido"><PageHeader categoria="CUMPLIMIENTO" titulo="Exportaciones" descripcion="Consultá y descargá los informes de la organización seleccionada."><label className="selector-organizacion"><span>Organización</span><select value={orgId} onChange={e=>setOrgId(e.target.value)}>{orgs.map(o=><option key={o.id} value={o.id}>{o.nombre}</option>)}</select></label></PageHeader>{error&&<p className="mensaje mensaje-error" role="alert">{error}</p>}<section className="panel-estructura"><div className="exportaciones-grid"><button type="button" disabled={cargando||!orgId} onClick={()=>void ejecutar('el inventario de activos',()=>exportarInventario(orgId))}>Inventario de activos</button><button type="button" disabled={cargando||!orgId} onClick={()=>void ejecutar('los controles SOA',()=>exportarControlesSoa(orgId))}>Controles SOA</button><button type="button" disabled={cargando||!orgId} onClick={()=>void ejecutar('la evaluación SOA',()=>exportarSoa(orgId))}>Evaluación SOA</button><button type="button" disabled={cargando||!orgId} onClick={()=>void ejecutar('las brechas SOA',()=>exportarBrechas(orgId,'todas'))}>Brechas SOA</button></div>{cargando&&<p className="mensaje" role="status">Generando consulta…</p>}{resultado&&<><div className="acciones-exportacion"><button type="button" onClick={()=>descargar('informe-rsi.md',resultado,'text/markdown;charset=utf-8')}>Descargar Markdown</button><button type="button" onClick={()=>window.print()}>Guardar como PDF</button><button type="button" onClick={descargarCsv}>Descargar CSV</button></div><article className="vista-previa-exportacion">{vistaPrevia(resultado)}</article></>}</section></main></div> }
