import { useEffect, useMemo, useState } from 'react'
import { listarOrganizaciones, listarTrabajadores } from '../../organizacion/api/organizacionApi'
import type { Organizacion, Trabajador } from '../../organizacion/types/organizacion'
import { actualizarPolitica, crearPolitica, eliminarPolitica, listarPoliticas, type DatosPolitica, type Politica } from '../api/cumplimientoApi'
import '../cumplimiento.css'

export function PoliticasPage() {
  const [organizaciones, setOrganizaciones] = useState<Organizacion[]>([]); const [organizacionId, setOrganizacionId] = useState(''); const [trabajadores, setTrabajadores] = useState<Trabajador[]>([]); const [politicas, setPoliticas] = useState<Politica[]>([]); const [editando, setEditando] = useState<Politica | null>(null); const [titulo, setTitulo] = useState(''); const [descripcion, setDescripcion] = useState(''); const [version, setVersion] = useState('1.0'); const [estado, setEstado] = useState('BORRADOR'); const [responsableId, setResponsableId] = useState(''); const [fechaRevision, setFechaRevision] = useState(''); const [error, setError] = useState('')
  useEffect(() => { void Promise.all([listarOrganizaciones(new AbortController().signal), listarTrabajadores(), listarPoliticas()]).then(([o, t, p]) => { setOrganizaciones(o); setOrganizacionId(o[0]?.id ?? ''); setTrabajadores(t); setPoliticas(p) }).catch(() => setError('No se pudieron cargar los datos.')) }, [])
  const visibles = useMemo(() => politicas.filter((p) => p.organizacionId === organizacionId), [politicas, organizacionId]); const trabajadoresVisibles = trabajadores.filter((t) => t.unidadOrganizativa?.organizacionId === organizacionId)
  function limpiar() { setEditando(null); setTitulo(''); setDescripcion(''); setVersion('1.0'); setEstado('BORRADOR'); setResponsableId(''); setFechaRevision('') }
  function editar(p: Politica) { setEditando(p); setTitulo(p.titulo); setDescripcion(p.descripcion ?? ''); setVersion(p.version); setEstado(p.estado); setResponsableId(p.responsable?.id ?? ''); setFechaRevision(p.fechaRevision?.slice(0, 10) ?? '') }
  async function guardar(e: React.FormEvent) { e.preventDefault(); if (!organizacionId || !titulo.trim()) return; const d: DatosPolitica = { titulo: titulo.trim(), descripcion: descripcion.trim(), version, estado, fechaRevision: fechaRevision || undefined, ...(responsableId && { responsableId }) }; try { if (editando) await actualizarPolitica(editando.id, d); else await crearPolitica(organizacionId, d); setPoliticas(await listarPoliticas()); limpiar() } catch { setError('No se pudo guardar la política.') } }
  async function borrar(p: Politica) { if (!window.confirm(`¿Eliminar la política “${p.titulo}”?`)) return; try { await eliminarPolitica(p.id); setPoliticas(await listarPoliticas()) } catch { setError('No se pudo eliminar la política.') } }
  return <div className="aplicacion"><header className="barra-superior"><span className="marca"><span className="marca-simbolo">R</span><span className="marca-texto"><strong>RSI</strong><small>Gestión integrada</small></span></span><span className="entorno">Sistema de gestión</span></header><main className="contenido"><div className="encabezado-pagina"><div><p className="sobretitulo">CUMPLIMIENTO</p><h1>Políticas de seguridad</h1><p className="introduccion">Gestioná las políticas de la organización seleccionada.</p></div><label className="selector-organizacion"><span>Organización</span><select value={organizacionId} onChange={(e) => setOrganizacionId(e.target.value)}>{organizaciones.map((o) => <option key={o.id} value={o.id}>{o.nombre}</option>)}</select></label></div>{error && <p className="mensaje mensaje-error">{error}</p>}<section className="panel-estructura"><form className="formulario-cumplimiento" onSubmit={guardar}><h3>{editando ? 'Editar política' : 'Nueva política'}</h3><label>Título<input value={titulo} onChange={(e) => setTitulo(e.target.value)} required /></label><label>Versión<input value={version} onChange={(e) => setVersion(e.target.value)} /></label><label>Estado<select value={estado} onChange={(e) => setEstado(e.target.value)}><option>BORRADOR</option><option>ACTIVA</option><option>OBSOLETA</option></select></label><label>Responsable<select value={responsableId} onChange={(e) => setResponsableId(e.target.value)}><option value="">Sin responsable</option>{trabajadoresVisibles.map((t) => <option key={t.id} value={t.id}>{t.nombre}</option>)}</select></label><label>Fecha de revisión<input type="date" value={fechaRevision} onChange={(e) => setFechaRevision(e.target.value)} /></label><label className="campo-ancho">Descripción<textarea value={descripcion} onChange={(e) => setDescripcion(e.target.value)} rows={3} /></label><div className="formulario-acciones"><button type="submit">{editando ? 'Guardar cambios' : 'Crear política'}</button>{editando && <button type="button" onClick={limpiar}>Cancelar</button>}</div></form><div className="lista-cumplimiento">{visibles.map((p) => <article className="unidad-tarjeta" key={p.id}><div className="unidad-detalle"><span className="unidad-tipo">{p.estado} · v{p.version}</span><h3>{p.titulo}</h3><p>{p.descripcion || 'Sin descripción'} · Responsable: {p.responsable?.nombre ?? 'Sin responsable'}</p></div><div className="unidad-acciones"><button type="button" onClick={() => editar(p)}>Editar</button><button type="button" onClick={() => void borrar(p)}>Eliminar</button></div></article>)}</div></section></main></div>
}
