// Ejecutar desde la raíz: node frontend/checks/ui.cjs
// Datos simulados: no requiere credenciales ni modifica la API.
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
(async () => {
 const browser = await chromium.launch({ headless: true, channel: 'msedge' });
 const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
 const errores = []; page.on('pageerror', e => errores.push(e.message));
 const usuario = { id: 'demo', correo: 'demo@example.test', rol: 'ADMINISTRADOR', mfaConfirmado: true };
 await page.addInitScript(u => { localStorage.setItem('rsi_token', 'simulado'); localStorage.setItem('rsi_usuario', JSON.stringify(u)); }, usuario);
 let falloGuardar = true; let creado = null; let escrituras = 0;
 const simular = route => {
  const url = new URL(route.request().url());
  if (!url.pathname.startsWith('/api/v1/')) return route.continue();
  let data = [];
  if (route.request().method() === 'POST' && url.pathname.endsWith('/activos')) { escrituras++; if (falloGuardar) return route.fulfill({ status: 500, json: {} }); creado = { ...JSON.parse(route.request().postData()), id: 'nuevo', unidadOrganizativa: { id: 'unidad' }, procesos: [] }; return route.fulfill({ json: creado }); }
  if (route.request().method() === 'PATCH' && url.pathname.includes('/activos/')) { escrituras++; return route.fulfill({ json: {} }); }
  if (url.pathname.endsWith('/soa/controles')) data = [{controlId:'A.5.1',tema:'Políticas de seguridad',evaluacion:null}];
  if (url.pathname.endsWith('/auth/auditoria')) data = { eventos: [], total: 0 };
  if (url.pathname.endsWith('/auth/me')) data = usuario;
  if (url.pathname.endsWith('/kpis/resumen')) data = { activos: { total: 24, conResponsable: 20, porcentajeConResponsable: 83 }, riesgos: { abiertos: 8 }, vulnerabilidades: { abiertas: 12, criticas: 3 }, incidentes: { ABIERTO: 2, EN_CONTENCION: 1, CERRADO: 6 } };
  if (url.pathname.endsWith('/kpis/formulas')) data = [{ codigo: 'ACTIVOS', nombre: 'Activos registrados', unidad: 'CANTIDAD' }];
  if (url.pathname.endsWith('/kpis/indicadores')) data = [{ id: 'kpi', codigo: 'ACTIVOS', nombre: 'Inventario', descripcion: null, formula: 'ACTIVOS', meta: 25, activo: true }];
  if (url.pathname.endsWith('/organizaciones')) data = [{ id: 'org', nombre: 'Organización de prueba' }];
  if (url.pathname.endsWith('/unidades')) data = [{ id: 'unidad', nombre: 'Tecnología' }];
  if (url.pathname.endsWith('/activos')) data = Array.from({ length: 12 }, (_, i) => ({ id: `a${i}`, nombre: `Activo ${String(i + 1).padStart(2, '0')}`, tipo: 'Servidor', criticidad: i === 0 ? 'CRITICA' : 'MEDIA', clasificacion: 'INTERNO', unidadOrganizativa: { id: 'unidad' }, procesos: [] }));
  if (route.request().method() === 'GET' && url.pathname.endsWith('/activos') && creado) data.push(creado);
  return route.fulfill({ json: data });
 };
 await page.route('**/api/**', simular);
 await page.goto('http://127.0.0.1:5173');
 await page.getByRole('heading', { name: 'Requieren atención' }).waitFor();
 const tabla = page.getByRole('region', { name: 'Indicadores configurados', exact: true });
 await tabla.getByRole('cell', { name: 'Inventario ACTIVOS' }).waitFor();
 await tabla.getByRole('searchbox').fill('no existe');
 assert.equal(await tabla.locator('tbody tr').count(), 1);
 assert.match(await tabla.locator('tbody').innerText(), /No hay registros/);
 await tabla.getByRole('searchbox').fill('Inventario');
 await tabla.getByRole('button', { name: 'Indicador' }).click();
 assert.equal(await tabla.locator('th').first().getAttribute('aria-sort'), 'descending');
 await tabla.getByRole('searchbox').fill('');
 await page.evaluate(() => window.scrollTo(0, 0));
 await page.screenshot({ path: 'outputs/rsi-dashboard-desktop.png', fullPage: true });
 assert.equal(await page.locator('.barra-superior:visible').count(), 0);
 await page.getByRole('button', { name: 'Activos', exact: true }).click();
 await page.locator('.lista-registros article').first().waitFor();
 assert.equal(await page.locator('.lista-registros article').count(), 10);
 await page.getByRole('button', { name: 'Siguiente', exact: true }).click();
 assert.equal(await page.locator('.lista-registros article').count(), 2);
 await page.getByLabel('Estado o tipo').selectOption('CRITICA');
 assert.equal(await page.locator('.lista-registros article').count(), 1);
 await page.getByLabel('Estado o tipo').selectOption('');
 await page.getByRole('searchbox').fill('Activo 01');
 assert.equal(await page.locator('.lista-registros article').count(), 1);
 await page.getByRole('searchbox').fill('sin coincidencia');
 await page.getByRole('heading', { name: 'Sin coincidencias' }).waitFor();
 await page.getByRole('button', { name: 'Limpiar búsqueda' }).click();
 await page.getByLabel('Ordenar').selectOption('desc');
 assert.match(await page.locator('.lista-registros h3').first().innerText(), /Activo 12/);
 await page.evaluate(() => window.scrollTo(0, 0));
 await page.screenshot({ path: 'outputs/rsi-activos-desktop.png', fullPage: true });
 assert.equal(await page.locator('.formulario-activo:visible').count(), 0);
 const abrir = page.getByRole('button', { name: '＋ Nuevo activo', exact: true });
 await abrir.click();
 const asistente = page.getByRole('dialog');
 await asistente.getByRole('heading', { name: 'Nuevo activo', exact: true }).waitFor();
 await asistente.getByRole('button', { name: 'Revisar datos' }).click();
 assert.equal(await asistente.getByRole('region', { name: 'Revisión de datos' }).count(), 0);
 assert.equal(escrituras, 0);
 await asistente.getByLabel('Nombre', { exact: true }).fill('ZZ Activo nuevo');
 await asistente.getByLabel('Tipo', { exact: true }).fill('Servidor');
 await asistente.getByRole('button', { name: 'Revisar datos' }).click();
 await asistente.getByRole('region', { name: 'Revisión de datos' }).waitFor();
 assert.equal(escrituras, 0);
 await page.evaluate(() => window.scrollTo(0, 0));
 await page.screenshot({ path: 'outputs/rsi-asistente-revision.png', fullPage: true });
 await asistente.getByRole('button', { name: 'Guardar', exact: true }).click();
 await asistente.getByRole('alert').waitFor();
 assert.equal(await asistente.isVisible(), true);
 falloGuardar = false;
 await asistente.getByRole('button', { name: 'Guardar', exact: true }).click();
 await asistente.waitFor({ state: 'hidden' });
 await page.getByRole('heading', { name: 'ZZ Activo nuevo', exact: true }).waitFor();
 await page.locator('.lista-registros article').first().getByRole('button', { name: 'Editar', exact: true }).click();
 await asistente.getByRole('heading', { name: 'Editar activo', exact: true }).waitFor();
 assert.equal(await asistente.getByLabel('Nombre', { exact: true }).inputValue(), 'ZZ Activo nuevo');
 await page.keyboard.press('Escape');
 await asistente.waitFor({ state: 'hidden' });
 await abrir.click();
 await asistente.getByLabel('Nombre', { exact: true }).fill('Borrador');
 page.once('dialog', d => d.dismiss());
 await asistente.getByRole('button', { name: 'Cancelar', exact: true }).click();
 assert.equal(await asistente.isVisible(), true);
 page.once('dialog', d => d.accept());
 await page.keyboard.press('Escape');
 await asistente.waitFor({ state: 'hidden' });
 assert.equal(await abrir.evaluate(e => e === document.activeElement), true);

 await page.setViewportSize({ width: 390, height: 844 });
 await page.getByRole('button', { name: 'Colapsar navegación' }).click();
 assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
 await page.evaluate(() => window.scrollTo(0, 0));
 await page.screenshot({ path: 'outputs/rsi-activos-mobile.png', fullPage: true });
 await abrir.click();
 assert(await asistente.evaluate(e => e.scrollWidth <= e.clientWidth));
 await page.evaluate(() => window.scrollTo(0, 0));
 await page.screenshot({ path: 'outputs/rsi-asistente-mobile.png', fullPage: true });
 await page.keyboard.press('Escape');
 await asistente.waitFor({ state: 'hidden' });
 await page.getByRole('button', { name: 'Expandir navegación' }).click();
 assert.equal(await page.getByRole('navigation', { name: 'Navegación principal' }).isVisible(), true);
 await page.setViewportSize({ width: 1440, height: 1000 });
 for (const [modulo, nuevo] of [['Organizaciones','Nueva organización'], ['Unidades','Nueva unidad'], ['Trabajadores','Nuevo trabajador'], ['Procesos','Nuevo proceso'], ['RACI','Nueva asignación'], ['Vulnerabilidades','Nueva vulnerabilidad'], ['Riesgos','Nuevo riesgo'], ['Incidentes','Nuevo incidente'], ['Políticas','Nueva política'], ['Evidencias','Nueva evidencia'], ['Planes e hitos','Nuevo plan'], ['Procedimientos','Nuevo procedimiento'], ['Usuarios','Nuevo usuario'], ['Dashboard','Nuevo indicador']]) {
  await page.getByRole('navigation', { name: 'Navegación principal' }).getByRole('button', { name: modulo, exact: true }).click();
  await page.getByRole('button', { name: '＋ ' + nuevo, exact: true }).click();
  await page.getByRole('dialog').waitFor();
  await page.getByRole('dialog').getByRole('button', { name: 'Cancelar', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
 }
 for (const [width, height] of [[1366,768],[1440,900],[1920,1080],[768,1024]]) {
  await page.setViewportSize({width,height});
  for (const modulo of ['Dashboard','Activos','Usuarios','Auditoría','Seguridad de cuenta','Exportaciones','Evaluación SOA']) {
   await page.getByRole('navigation', { name: 'Navegación principal' }).getByRole('button', { name: modulo, exact: true }).click();
   await page.locator('main h1').waitFor();
   assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), modulo + ': desborde a ' + width);
   await page.evaluate(() => window.scrollTo(0,0));
   if (modulo === 'Dashboard' || width === 1366) await page.screenshot({path: 'outputs/rsi-' + modulo.replaceAll(' ','-') + '-' + width + '.png', fullPage:true});
  }
 }
 await page.setViewportSize({width:1440,height:900});
 await page.getByRole('button', { name: 'Colapsar navegación' }).click();
 assert.equal(await page.getByRole('button', {name:'Activos',exact:true}).isVisible(),true);
 await page.getByRole('button', {name:'Activos',exact:true}).click();
 await page.getByRole('heading', {name:'Inventario de activos',exact:true}).waitFor();
 await page.locator('.lista-registros article').first().waitFor();
 await page.screenshot({path:'outputs/rsi-sidebar-colapsada.png'});
 const lectorPage = await browser.newPage({viewport:{width:1366,height:768}});
 usuario.rol = 'LECTOR';
 await lectorPage.addInitScript(u => {localStorage.setItem('rsi_token','simulado');localStorage.setItem('rsi_usuario',JSON.stringify(u));}, usuario);
 await lectorPage.route('**/api/**',simular);
 await lectorPage.goto('http://127.0.0.1:5173');
 await lectorPage.getByRole('heading',{name:'Inventario de activos',exact:true}).waitFor();
 assert.equal(await lectorPage.getByRole('button',{name:'＋ Nuevo activo',exact:true}).count(),0);
 assert.equal(await lectorPage.getByRole('button',{name:'Editar',exact:true}).count(),0);
 assert.equal(await lectorPage.getByRole('button',{name:'Usuarios',exact:true}).count(),0);
 await lectorPage.getByRole('button',{name:'Evaluación SOA',exact:true}).click();
 await lectorPage.getByRole('button',{name:'A.5.1'}).click();
 assert.equal(await lectorPage.getByRole('dialog').count(),0);
 assert.deepEqual(errores, []);
 await browser.close();
 console.log('UI verificada: listados, asistentes en 15 módulos, validación, revisión, error y éxito al guardar, descarte, teclado y móvil.');
})().catch(e => { console.error(e); process.exit(1); });
